// auto-generated by build-mdx-index.mjs
export type PostMeta = { slug: string; title: string; date: string; tags: string[] };
export const postsMeta: PostMeta[] = [
  {
    "slug": "hello",
    "title": "Hello",
    "date": "2025-11-02T00:00:00.000Z",
    "tags": [
      "test"
    ]
  }
];

export const postsMap: Record<string, () => Promise<any>> = {
  "hello": () => import("../../../content/posts/hello.mdx") 
};
